//==================================================================================================
// This is the Jenkins pipeline script for building the OMAR services application (formerly all-app).
// Environment varialbes that MUST be passed in by Jenkins:
//    OSSIM_GIT_BRANCH: The tag of the branch to be built. Typically dev or master.
//
// Environment varaibles that MUST be set in the Jenkins global environment (manage jenkins -> configure system -> environment varaibles)
//    ARTIFACTORY_USER: The user to use when pushing artifacts
//    ARTIFACTORY_PASSWORD: The password to use when pushing artifacts
//    OPENSHIFT_USERNAME: The user to use logging into the docker registry
//    OPENSHIFT_PASSWORD: The password to use logging into the docker registry
//==================================================================================================

// TODO: get to run on any node
node("master"){
    def workspaceDir = pwd()
    def appName = "omar-services"
    def omarCommonProjName = "omar-common"
    env.OMAR_COMMON_PROPERTIES="${workspaceDir}/${omarCommonProjName}/omar-common-properties.gradle"
    env.O2_DEV_HOME=pwd()

    stage("Checkout"){
        dir("ossim-ci") {
            git branch: "${OSSIM_GIT_BRANCH}", url: "https://github.com/ossimlabs/ossim-ci.git"
        }
        dir("ossim-core") {
            git branch: "${OSSIM_GIT_BRANCH}", url: "https://github.com/ossimlabs/omar-core.git"
        }
        dir("ossim-ingest-metrics") {
            git branch: "${OSSIM_GIT_BRANCH}", url: "https://github.com/ossimlabs/omar-ingest-metrics.git"
        }
        dir("ossim-download") {
            git branch: "${OSSIM_GIT_BRANCH}", url: "https://github.com/ossimlabs/omar-download.git"
        }
        dir("ossim-geoscript") {
            git branch: "${OSSIM_GIT_BRANCH}", url: "https://github.com/ossimlabs/omar-geoscript.git"
        }
        dir("ossim-mensa") {
            git branch: "${OSSIM_GIT_BRANCH}", url: "https://github.com/ossimlabs/omar-mensa.git"
        }
        dir("ossim-oms") {
            git branch: "${OSSIM_GIT_BRANCH}", url: "https://github.com/ossimlabs/omar-oms.git"
        }
        dir("ossim-raster") {
            git branch: "${OSSIM_GIT_BRANCH}", url: "https://github.com/ossimlabs/omar-raster.git"
        }
        dir("ossim-stager") {
            git branch: "${OSSIM_GIT_BRANCH}", url: "https://github.com/ossimlabs/omar-stager.git"
        }
        dir("ossim-superoverlay") {
            git branch: "${OSSIM_GIT_BRANCH}", url: "https://github.com/ossimlabs/omar-superoverlay.git"
        }
        dir("ossim-video") {
            git branch: "${OSSIM_GIT_BRANCH}", url: "https://github.com/ossimlabs/omar-video.git"
        }
        dir("ossim-wfs") {
            git branch: "${OSSIM_GIT_BRANCH}", url: "https://github.com/ossimlabs/omar-wfs.git"
        }
        dir("ossim-wms") {
            git branch: "${OSSIM_GIT_BRANCH}", url: "https://github.com/ossimlabs/omar-wms.git"
        }
        dir(appName) {
            git branch: "${OSSIM_GIT_BRANCH}", url: "https://github.com/ossimlabs/${appName}.git"
        }

        dir(omarCommonProjName) {
            git branch: "${OSSIM_GIT_BRANCH}", url: "https://github.com/ossimlabs/${omarCommonProjName}.git"
        }

        notifyObj = load "${workspaceDir}/ossim-ci/jenkins/pipeline/notify.groovy"
    }

    try {
      stage ("Publish App Artifactory")
      {
          withCredentials([[$class: 'UsernamePasswordMultiBinding', 
                            credentialsId: 'artifactoryCredentials',
                            usernameVariable: 'ARTIFACTORY_USER', 
                            passwordVariable: 'ARTIFACTORY_PASSWORD']])
            {
                    sh """
                    pushd ${workspaceDir}/${appName}
                    ./gradlew :${appName}-app:artifactoryPublish
                    popd
                    """
            }
      }

      stage ("Publish Docker App")
      {
        withCredentials([[$class: 'UsernamePasswordMultiBinding', 
                        credentialsId: 'dockerCredentials',
                        usernameVariable: 'OPENSHIFT_USERNAME', 
                        passwordVariable: 'OPENSHIFT_PASSWORD']])
        {
            // Run all tasks on the app. This includes pushing to OpenShift and S3.
            sh """
            pushd ${workspaceDir}/${appName}
            ./gradlew :${appName}-app:${GRADLE_TASK}
            popd
            """
        }
      }
    }
    catch(e){
        echo e.toString()
        currentBuild.result = "FAILED"
        notifyObj?.notifyFailed()
    }
  stage("Clean Workspace"){
     step([$class: 'WsCleanup'])
  }
}
